development: 
  cloud_name: "day0s6gn4"
  api_key: "846897557959156"
  api_secret: "GllQY22-GzEdALA9NVgr6gmIpeA"
  secure: true

production:
  cloud_name: "day0s6gn4"
  api_key: "846897557959156"
  api_secret: "GllQY22-GzEdALA9NVgr6gmIpeA"
  secure: true